<?php
if ($block->getCollectionCount() > 0 && $block->getIsQaEnable()) { ?>
    <div id="ask_feature_div" class="celwidget" data-feature-name="ask" data-csa-c-id="o7mvuh-ab2yvf-pr3hwf-mrbs13" data-cel-widget="ask_feature_div">
        <span class="askPipe"> | </span>
        <span cel_widget_id="ask-atf-link-desktop" class="celwidget" data-csa-c-id="ko52ew-h6n7w4-ojb4k-m1qil" data-cel-widget="ask-atf-link-desktop">
            <a id="askATFLink" class="a-link-normal askATFLink" href="#Ask"> <span class="a-size-base"> <?php echo $block->getCollectionCount(); ?> answered questions </span> </a> </span>
    </div>
<?php }
?>