
<div class="brand-wrapper">
    <img src="<?php echo $block->getLogoSrc();?>" alt="logo" ><br>
</div>
<head>
    <title>Address form</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/main.css">
    <script src="js/main.js" defer></script>
    <link rel="stylesheet" href="style.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false&libraries=places"></script>
    <script type="text/javascript" src="https://rawgit.com/Logicify/jquery-locationpicker-plugin/master/dist/locationpicker.jquery.js"></script>
<!--    <script src="script.js"></script>-->
</head>

<!--Location: <input type="text" id="location" style="width: 200px"/>-->
<!--Lat <input type="text" id="lat" style="width: 200px"/>-->
<!--Long: <input type="text" id="lng" style="width: 200px"/>-->
<div id="us2" style="width: 1400px; height: 700px;margin-top: 3%;border-radius: 25px;">

</div>
<!--<button onclick="getLocation()">get loc</button>-->

<form action="<?php echo $block->getUrl("login/location/submit");?>" method="post"">
<input type="hidden" id="lat1" name="lat" value="">
<input type="hidden" id="lng1" name="lng" value="">
<button class="location-submit">Submit</button>

<p id="demo"></p>
</form>
<form action="<?php echo $block->getUrl("login/location/submit");?>" method="post">

    <h1>Address form</h1>

    <section>
        <label for="name">Name</label>
        <input id="name" name="name" autocomplete="name" maxlength="100" pattern="[\p{L} \-\.]+" required>
    </section>

    <section>
        <label for="address">Plot No</label>
        <input id="address" name="plot no" autocomplete="address" maxlength="50" required></input>
    </section>
    <section>
        <label for="address">Apartment name</label>
        <input id="address" name="apartment name" autocomplete="address" maxlength="50" required></input>
    </section>
    <section>
        <label for="postal-code">ZIP or postal code (optional)</label>
        <input id="postal-code" name="postal-code" autocomplete="postal-code" maxlength="20">
    </section>
    <a id="save-address" class="btn btn-primary" type="submit" href="<?php echo $block->getUrl("login/validate/");?>"> Save address</a>


    <script>
    var x = document.getElementById("demo");

    $(".location-submit").on("click",function(){
        $("#lat1").val(lat);
        $("#lng1").val(lng);
    });


    function showPosition(position) {
        x.innerHTML="Latitude: " + position.coords.latitude +
            "<br>Longitude: " + position.coords.longitude;
    }
</script>


<script>
    var lat;
    var lng;
    $(function() {
        if (navigator.geolocation) {
            var location_timeout = setTimeout("geolocFail()", 10000);

            navigator.geolocation.getCurrentPosition(function(position) {
                clearTimeout(location_timeout);

                lat = position.coords.latitude;
                lng = position.coords.longitude;
                console.log(position.coords.latitude)
                $('#us2').locationpicker({

                    location: {latitude: lat, longitude: lng},
                    radius: 0,
                    inputBinding: {
                        latitudeInput: $('#lat'),
                        longitudeInput: $('#lng'),
                        locationNameInput: $('#location')
                    },
                    enableAutocomplete: true,
                    onchanged: function(currentLocation, radius, isMarkerDropped) {
                        alert("Location changed. New location (" + currentLocation.latitude + ", " + currentLocation.longitude + ")");
                    }
                });
                geocodeLatLng(lat, lng);
            }, function(error) {
                clearTimeout(location_timeout);
                geolocFail();
            });
        } else {
            // Fallback for no geolocation
            geolocFail();
        }



    });

</script>



