<form action="<?php echo $block->getUrl("registration/productregistration/post");?> " method="post"">
    <label for="dop">Date of purchase:</label>
    <input type="date" id="dop" name="dop" required><br>
    <label for="name">Product name:</label>
    <input type="text" id="name" name="name" required><br>
    <label for="sku">sku:</label>
    <input type="text" id="sku" name="sku" required><br>
    <label for="contactno">Contact no:</label>
    <input type="number" id="contactno" name="contactno"  required><br>
    <label for="vendor">Vendor:</label>
    <input type="text" id="vendor" name="vendor" required><br>
    <label for="email">Email:</label>
    <input type="email" id="email" name="email" required><br>
    <label for="address">Address:</label>
    <input type="text" id="address" name="address" required><br>
    <input type="submit" value="Submit">
</form>
