<?php if (!$block->getCollectionCount())
    {
       return;
    }
    ?>
<div id="askReverseWeblab_feature_div" class="celwidget" data-feature-name="askReverseWeblab" data-csa-c-id="k9w6h5-ibf38k-5rbsg2-4i66pf" data-cel-widget="askReverseWeblab_feature_div">
    <span class="askPipe"> | </span>
    <span cel_widget_id="ask-atf-link-desktop" class="celwidget" data-csa-c-id="ghcygw-ccvy1b-74ttd1-9y0b10" data-cel-widget="ask-atf-link-desktop">
    <a id="askATFLink" class="a-link-normal askATFLink" href="#myform"> <span class="a-size-base"><?php echo $block->getCollectionCount ();?> questions </span> </a> </span>
</div>
