
<img src="<?php echo $block->getLogoSrc();?>"><br>






<main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
    <div class="container">
        <div class="card login-card">
            <div class="row no-gutters">
                <div class="col-md-5">
                    <img src="https://www.bootstrapdash.com/demo/login-template-free-2/assets/images/login.jpg" style="
    width: 30%;
" alt="login" class="login-card-img">
                    <p class="text-white font-weight-medium text-center flex-grow align-self-end footer-link text-small">
                        Free <a href="https://www.bootstrapdash.com/" target="_blank" class="text-white">Bootstrap dashboard templates</a> from Bootstrapdash
                    </p>
                </div>
                <div class="col-md-7">
                    <div class="card-body">
                        <div class="brand-wrapper">
                            <img src="<?php echo $block->getLogoSrc();?>" alt="logo" ><br>
                        </div>
                        <?php
                        if($block->showError()){ ?>
                            <p>Invalid OTP. Please try again</p>
                       <?php } 
                        ?>

                        <p class="login-card-description">Please enter the OTP sent on <?php echo $block->getPhone();?></p>
                        <form action="<?php echo $block->getUrl("login/verify/otp");?>" method="post"">
                        <div class="form-group mb-4">
                            <label for="mobile" class="sr-only"></label>
                            <input type="tel" name="otp" id="phone" class="form-control" minlength="4"  maxlength="4" placeholder=" Your OTP" required >
                        </div>

                        <input name="continue" id="continue" class="btn btn-block login-btn mb-4" type="submit" value="Submit">
                        <div class="otp-form__actions">
<!--                            <div>-->
<!--                        	<span id="resending_otp" class="hide">-->
<!--                                Resending OTP-->
<!--                                <span class="ic-dots"></span>-->
<!--                            </span>-->
<!--                                <span id="sent_otp" class="hide">-->
<!--                                <span class="ic-checkmark"></span>-->
<!--                                Sent new OTP-->
<!--                            </span>-->
<!--                            </div>-->
                            <a class="pipe-sep" style="font-size: 14px" id="resend_otp" href="<?php echo $block->getUrl("login/verify/sendotp");?>" >Resend OTP</a> | 
                            <a id="wrong-number" style="font-size: 14px" class="otp-toggle" href="<?php echo $block->getUrl("login/");?>">Entered wrong number?</a>
                        </div>
                        </form>

                        <nav class="login-card-footer-nav">
                            <a href="#!">Terms of use.</a>
                            <a href="#!">Privacy policy</a>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <!-- <div class="card login-card">
          <img src="assets/images/login.jpg" alt="login" class="login-card-img">
          <div class="card-body">
            <h2 class="login-card-title">Login</h2>
            <p class="login-card-description">Sign in to your account to continue.</p>
            <form action="#!">
              <div class="form-group">
                <label for="email" class="sr-only">Email</label>
                <input type="email" name="email" id="email" class="form-control" placeholder="Email">
              </div>
              <div class="form-group">
                <label for="password" class="sr-only">Password</label>
                <input type="password" name="password" id="password" class="form-control" placeholder="Password">
              </div>
              <div class="form-prompt-wrapper">
                <div class="custom-control custom-checkbox login-card-check-box">
                  <input type="checkbox" class="custom-control-input" id="customCheck1">
                  <label class="custom-control-label" for="customCheck1">Remember me</label>
                </div>
                <a href="#!" class="text-reset">Forgot password?</a>
              </div>
              <input name="login" id="login" class="btn btn-block login-btn mb-4" type="button" value="Login">
            </form>
            <p class="login-card-footer-text">Don't have an account? <a href="#!" class="text-reset">Register here</a></p>
          </div>
        </div> -->
    </div>
</main>


<style >
    .min-vh-100 {
        min-height: 75vh!important;
    }
</style>
