<!--
Front-End Design
Ui Design
Website: www.cupcom.com.br
-->
<link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/af562a2a63.js" crossorigin="anonymous"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="stylesheet">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<!--<img src="--><?php //echo $block->getLogoSrc();?><!--"><br>-->

<header style="width: 1700px"
<!-- contact content -->

<!-- / contact content -->
<div class="container">
    <img src="<?php echo $block->getLogoSrc();?>"><br>
    </i></strong>
    <div>
        <i class="fa fa-map-marker fa-3 header-loc" href="#" data-dismiss="modal" data-backdrop="false" aria-hidden="true" data-toggle="modal" data-target="#myModal">
        </i>

        <div class="modal" id="myModal" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Modal Header</h4>
                    </div>
                    <div class="modal-body">
                        <p>
                            <a href="<?php echo $block->getUrl("login/location"); ?>">Add new address</a>
                            <?php $list= $block->getCustomerAddresses();?>
                        <ul class="list-group">
                            <?php
                            foreach ($list as $value)
                            {?>
                                <li class="list-group-item">
                                    <a href="<?php echo $block->getUrl("login/address").'?adressid='.$value->getId();?>">
                                        <?php echo $value->getCustomAttribute('plot_no')->getValue() ;
                                        if ($value->getCustomAttribute('apartment_name')){
                                            echo  ',' . $value->getCustomAttribute('apartment_name')->getValue();
                                        }

                                        echo     ',' . $value->getStreet()[0] . ',' . $value->getStreet()[1] . ',' . $value->getCity(); ?>
                                </li>
                                <?php
                            }
                            ?>

                        </ul>

                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>

        <p class="header-address">  <?php echo $block->getDefaultAddress(); ?> </p>
    </div>


    <div class="form-group has-search">
        <span class="fa fa-search form-control-feedback"></span>
        <input type="text" class="form-control" placeholder="Search">
    </div>

    <div class="input-group">
        <!-- Bootstrap CSS -->
        <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
        <!-- Font Awesome CSS -->
        <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
        <nav class="nav-content">

            <!-- nav -->
            <ul class="nav-content-list">
                <li class="nav-content-item account-login">
                    <label class="open-menu-login-account" for="open-menu-login-account">

                        <input class="input-menu" id="open-menu-login-account" type="checkbox" name="menu" />

                        <i class="fas fa-user-circle"></i><span class="login-text"><strong> <a href="<?php echo $block->getUrl("account");?>">My Account</a> </strong></span> <span class="item-arrow"></span>
                    </label>
            </ul>
            </li>
            <li class="nav-content-item"><a class="cart" href="<?php echo $block->getUrl("cart");?>"><i class="fas fa-shopping-cart"></i></a></li>
            <!-- call to action -->
            </ul>
        </nav>
    </div>
</div>
</header>






<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


        </script>




