<?php $count= $block->getSearchResults();
if($count>0)
{
    return;
}
if($block->getIsitEnable()==1)
{
?>

<form action="<?php echo $block->getUrl("suggestionbox/index/index");?>" method="post">
    <label for="fname">Suggestion:</label><br>
    <input type="text" id="suggestion" name="suggestion" ><br>
    <input type="submit" value="Submit">
</form>
<?php
}
?>
<!--$block->getIsitEnable()==0-->
