


<div id="carouselExampleControls" class="carousel slide" data-interval="<?php echo $block->getDelay() ?>" data-ride="carousel">

    <div class="carousel-inner" >
        <?php $banners = $block->getBanner3();
        $flag = 0;
        foreach($banners as $value){ ?>
            <div class="carousel-item item <?php if($flag == 0){ echo "active"; } ?> ">
                <a href="<?php echo $value->getLink(); ?>">
                    <img class="d-block w-100" href="#" style="margin-top: 30%" src="<?php echo $value->getImage(); ?>" alt="<?php echo $value->getAlttext(); ?>">
                </a>
            </div>
            <?php
            $flag = $flag +1;
        }
        ?>

    </div>
</div>
<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
</a>
<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
</a>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

