<?php

?>

<div class="home-cat">

<section class="section-products">
    <div class="container home-cat-container">
        <div class="row justify-content-center text-center">
            <div class="col-md-8 col-lg-6">

            </div>
        </div>
        <div class="row home-cat-row">
            <!-- Single Product -->
            <div class="col-md-6 col-lg-4 col-xl-3">
                <div id="product-1" class="single-product">
                    <div class="part-1">

                    </div>
                    <div class="part-2">
                        <h3 class="product-title">Here Product Title</h3>
                    </div>
                </div>
            </div>
            <!-- Single Product -->
            <div class="col-md-6 col-lg-4 col-xl-3">
                <div id="product-2" class="single-product">
                    <div class="part-1">
                        <span class="discount">15% off</span>

                    </div>
                    <div class="part-2">
                        <h3 class="product-title">Here Product Title</h3>

                    </div>
                </div>
            </div>
            <!-- Single Product -->
            <div class="col-md-6 col-lg-4 col-xl-3">
                <div id="product-3" class="single-product">
                    <div class="part-1">

                    </div>
                    <div class="part-2">
                        <h3 class="product-title">Here Product Title</h3>

                    </div>
                </div>
            </div>
            <!-- Single Product -->
            <div class="col-md-6 col-lg-4 col-xl-3">
                <div id="product-4" class="single-product">
                    <div class="part-1">
                        <span class="new">new</span>

                    </div>
                    <div class="part-2">
                        <h3 class="product-title">Here Product Title</h3>

                    </div>
                </div>
            </div>
            <!-- Single Product -->
            <div class="col-md-6 col-lg-4 col-xl-3">
                <div id="product-1" class="single-product">
                    <div class="part-1">

                    </div>
                    <div class="part-2">
                        <h3 class="product-title">Here Product Title</h3>

                    </div>
                </div>
            </div>
            <!-- Single Product -->
            <div class="col-md-6 col-lg-4 col-xl-3">
                <div id="product-2" class="single-product">
                    <div class="part-1">
                        <span class="discount">15% off</span>

                    </div>
                    <div class="part-2">
                        <h3 class="product-title">Here Product Title</h3>

                    </div>
                </div>
            </div>
            <!-- Single Product -->
            <div class="col-md-6 col-lg-4 col-xl-3">
                <div id="product-3" class="single-product">
                    <div class="part-1">

                    </div>
                    <div class="part-2">
                        <h3 class="product-title">Here Product Title</h3>

                    </div>
                </div>
            </div>
            <!-- Single Product -->
            <div class="col-md-6 col-lg-4 col-xl-3">
                <div id="product-4" class="single-product">
                    <div class="part-1">
                        <span class="new">new</span>

                    </div>
                    <div class="part-2">
                        <h3 class="product-title">Here Product Title</h3>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</div>
