<!--
Front-End Design
Ui Design
Website: www.cupcom.com.br
-->
<link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/af562a2a63.js" crossorigin="anonymous"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="stylesheet">

<!--<img src="--><?php //echo $block->getLogoSrc();?><!--"><br>-->



<header style="width: 1700px"
    <!-- contact content -->

    <!-- / contact content -->
    <div class="container">
        <img src="<?php echo $block->getLogoSrc();?>"><br>

        <!-- logo -->
<!--        <strong class="logo"><i class="fas fa-heart">-->

            </i></strong>
        <!-- open nav mobile -->
        <div>
            <i class="fa fa-map-marker fa-3 header-loc" aria-hidden="true"></i>
          <p class="header-address">  <?php echo $block->getDefaultAddress(); ?> </p>
        </div>


        <div class="form-group has-search">
            <span class="fa fa-search form-control-feedback"></span>
            <input type="text" class="form-control" placeholder="Search">
        </div>


        <!--search -->
<!--        <label class="open-search" for="open-search">-->
<!--            <i class="fas fa-search"></i>-->
<!--            <input class="input-open-search" id="open-search" type="checkbox" name="menu" />-->

                <div class="input-group">
                    <!-- Bootstrap CSS -->
                    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
                    <!-- Font Awesome CSS -->
                    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>


<!--                    <div class="input-group">-->
<!--                        <input type="text" class="form-control" placeholder="Search prodcut">-->
<!--                        <div class="input-group-append">-->
<!--                            <button class="btn btn-secondary" type="button">-->
<!--                                <i class="fa fa-search"></i>-->
<!--                            </button>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->


<!--        </label>-->
        <!-- // search -->

        <nav class="nav-content">

            <!-- nav -->
            <ul class="nav-content-list">
                <li class="nav-content-item account-login">
                    <label class="open-menu-login-account" for="open-menu-login-account">

                        <input class="input-menu" id="open-menu-login-account" type="checkbox" name="menu" />

                        <i class="fas fa-user-circle"></i><span class="login-text"><strong> <a href="<?php echo $block->getUrl("Account");?>">My Account</a> </strong></span> <span class="item-arrow"></span>

                        <!-- submenu -->
<!--                        <ul class="login-list">-->
<!--                            <li class="login-list-item"><a href="https://www.cupcom.com.br/">My account</a></li>-->
<!--                            <li class="login-list-item"><a href="https://www.cupcom.com.br/">Create account</a></li>-->
<!--                            <li class="login-list-item"><a href="https://www.cupcom.com.br/">logout</a></li>-->
                    </label>
            </ul>
            </li>
            <li class="nav-content-item"><a class="cart" href="<?php echo $block->getUrl("Cart");?>"><i class="fas fa-shopping-cart"></i></a></li>
            <!-- call to action -->
            </ul>
        </nav>
    </div>
</header>

<div id="carouselExampleControls" class="carousel slide" data-interval="1000" data-ride="carousel">
    <div class="carousel-inner" >
<?php $banners = $block->getBanners();
$flag = 0;
foreach($banners as $value){ ?>
<div class="carousel-item item <?php if($flag == 0){ echo "active"; } ?> ">
    <img class="d-block w-100" src="<?php echo $value->getImage(); ?>" alt="<?php echo $value->getAlttext(); ?>">
</div>
  <?php
    $flag = $flag +1;
}
?>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<!--        margin-left: 52px;-->
<!--        margin-top: -65px;-->
