<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,700&subset=latin-ext" rel="stylesheet">



<!--Item slider text-->

<div class="container" style="display: inline">
    <div class="row" id="slider-text">
        <div class="col-md-6" >
            <h2><?php echo $block->getTitle(); ?></h2>
        </div>
    </div>
</div>

<!-- Item slider-->
<div class="container-fluid" style="position: relative; right: -19%">

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="carousel carousel-showmanymoveone slide" id="itemslider">
                <div class="carousel-inner">
                    <?php $banners = $block->getList2();
                    $flag = 0;
                    foreach($banners as $value){
                    if($value->getEnable())
                    {
                    $product=$block->getProductInfo($value->getProductid());
                    $base=$block->getBase($product);
                    if($flag==0){ ?>
                    <div class="item active"> <?php } else{?>
                        <div class="item"> <?php } ?>
                            <div class="col-xs-12 col-sm-6 col-md-2">
                                <a href="<?php echo $product->getProductUrl();?>"><img src=<?php echo $base;?> class="img-responsive center-block"></a>
                                <h4 class="text-center"><?php echo $product->getName();?></h4>
                                <h5 class="text-center"><?php echo $product->getPrice();?></h5>
                            </div>
                        </div>
                        <?php
                        $flag=$flag+1;
                        }
                        }

                        ?>
                    </div>

                    <div id="slider-control">
                        <a class="left carousel-control" href="#itemslider" data-slide="prev"><img src="https://cdn0.iconfinder.com/data/icons/website-kit-2/512/icon_402-512.png" alt="Left" class="img-responsive"></a>
                        <a class="right carousel-control" href="#itemslider" data-slide="next"><img src="http://pixsector.com/cache/81183b13/avcc910c4ee5888b858fe.png" alt="Right" class="img-responsive"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Item slider end-->
    <br/><br/>
    <!--<footer class="bg-info">-->
    <!--    <p class="text-center">-->
    <!--        &copy; <a href="https://www.facebook.com/maruf.al.bashir" target="_blank" >Maruf-Al Bashir 2020</a>-->
    <!--    </p>-->
    <!--</footer>-->
    <script>
        $(document).ready(function(){

            $('#itemslider').carousel({ interval: 3000 });

            // $('.carousel-showmanymoveone .item').each(function(){
            //     var itemToClone = $(this);
            //
            //     for (var i=1;i<6;i++) {
            //         itemToClone = itemToClone.next();
            //
            //     if (!itemToClone.length) {
            //          itemToClone = $(this).siblings(':first');
            //         }
            //
            //      itemToClone.children(':first-child').clone()
            //            .addClass("cloneditem-"+(i))
            //            .appendTo($(this));
            //    }
            // });
        });

    </script>
