<h1>Registration form</h1>


<form action="<?php echo $block->getUrl('registration/index/post'); ?>" method="post" id="form1">
    <label for="sno">Product serial no:</label>
    <input type="text" id="sno" name="sno" required ><br><br>
    <label for="dop">Date of purchase:</label>
    <input type="text" id="dop" name="dop" required ><br><br>
    <label for="vendor">Vendor name:</label>
    <input type="text" id="vendor" name="vendor" required ><br><br>
    <label for="Name">Name:</label>
    <input type="text" id="Name" name="Name" required ><br><br>
    <label for="Email">Email id:</label>
    <input type="text" id="Email" name="Email" required ><br><br>
    <label for="Address">Address:</label>
    <input type="text" id="Address" name="Address" required ><br><br>
    <input type="submit" value="Submit">
</form>
