<?php
$productCollection = $block->getProductCollection();
// print_r($productCollection);
// exit
// print_r(count($productCollection));
// echo "<pre>";
 foreach ($productCollection as $product) 
{

    $url = $block->getProductImage($product);
    // print_r($url);
    // echo "<br>";
    // echo "<br>";
    ?>
    <li class="item product product-item">
  <div class="product-item-info" id="product-item-info_5" data-container="product-grid">
    <a href="<?php echo $product->getProductUrl(); ?>" class="product photo product-item-photo" tabindex="-1">
      <span class="product-image-container product-image-container-5" style="width: 240px;">
        <span class="product-image-wrapper" style="padding-bottom: 125%;">
          <img class="product-image-photo" src="<?php echo $url; ?>" loading="lazy" width="240" height="300" alt="earring 2">
        </span>
      </span>
      <style>
        .product-image-container-5 {
          width: 240px;
        }

        .product-image-container-5 span.product-image-wrapper {
          padding-bottom: 125%;
        }
      </style>
      <script type="text/javascript">
        prodImageContainers = document.querySelectorAll(".product-image-container-5");
        for (var i = 0; i < prodImageContainers.length; i++) {
          prodImageContainers[i].style.width = "240px";
        }
        prodImageContainersWrappers = document.querySelectorAll(".product-image-container-5  span.product-image-wrapper");
        for (var i = 0; i < prodImageContainersWrappers.length; i++) {
          prodImageContainersWrappers[i].style.paddingBottom = "125%";
        }
      </script>
    </a>
    <div class="product details product-item-details">
      <strong class="product name product-item-name">
        <a class="product-item-link" href="http://mysite.mg/earring-1.html"> <?php echo $product->getName(); ?></a>
      </strong>
      <div class="price-box price-final_price" data-role="priceBox" data-product-id="5" data-price-box="product-id-5">
        <span class="price-container price-final_price tax weee">
          <span id="product-price-5" data-price-amount="66" data-price-type="finalPrice" class="price-wrapper ">
            <span class="price"> <?php echo $product->getPrice(); ?> </span>
          </span>
        </span>
      </div>
      <div class="product-item-inner">
        <div class="product actions product-item-actions">
          <div class="actions-primary">
            <form data-role="tocart-form" data-product-sku="earring-1" action="http://mysite.mg/checkout/cart/add/uenc/aHR0cDovL215c2l0ZS5tZy9qd2Vscy5odG1s/product/5/" method="post">
              <input type="hidden" name="product" value="5">
              <input type="hidden" name="uenc" value="aHR0cDovL215c2l0ZS5tZy9jaGVja291dC9jYXJ0L2FkZC91ZW5jL2FIUjBjRG92TDIxNWMybDBaUzV0Wnk5cWQyVnNjeTVvZEcxcy9wcm9kdWN0LzUv">
              <input name="form_key" type="hidden" value="8uKsVv97rpbfQuQY">
              <button type="submit" title="Add to Cart" class="action tocart primary">
                <span>Add to Cart</span>
              </button>
            </form>
          </div>
          <div data-role="add-to-links" class="actions-secondary">
            <a href="#" class="action towishlist" title="Add to Wish List" aria-label="Add to Wish List" data-post="{&quot;action&quot;:&quot;http:\/\/mysite.mg\/wishlist\/index\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:5,&quot;uenc&quot;:&quot;aHR0cDovL215c2l0ZS5tZy9qd2Vscy5odG1s&quot;}}" data-action="add-to-wishlist" role="button">
              <span>Add to Wish List</span>
            </a>
            <a href="#" class="action tocompare" title="Add to Compare" aria-label="Add to Compare" data-post="{&quot;action&quot;:&quot;http:\/\/mysite.mg\/catalog\/product_compare\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;5&quot;,&quot;uenc&quot;:&quot;aHR0cDovL215c2l0ZS5tZy9qd2Vscy5odG1s&quot;}}" role="button">
              <span>Add to Compare</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</li>

<?php    
}
?>
