<?php
if ($block->getEnable())
{?>
<form action="<?php echo $block->getUrl("contactus/post"); ?>" method="post">
<?php
if ($block->getEnablename())
{?>
  <label for="fname">name:</label><br>
  <input type="text" id="fname" name="name" required><br>
  <?php
}
if ($block->getEnableemail())
{?>
  <label for="lname">emailid:</label><br>
  <input type="email" id="emailid" name="emailid" required>
  <?php
}
if ($block->getEnablephone())
{?>
  <label for="fname">phone:</label><br>
  <input type="text" id="phone" name="phone" pattern="[0-9]{10}" required><br>
  <?php
}
if ($block->getEnablecomment())
{?>
  <label for="lname">comment:</label><br>
  <input type="text" id="comment" name="comment" min="5" max="100" required>
  <?php }
  ?>
  <input type="submit" value="Submit">
</form>
<?php } 
?>
