
<?php
if (!$block->getEmiEnable()) {
    return;
}
?>
<div class="popup" onclick="myFunction()">Emi
<span class="popuptext" id="myPopup">

    <table style="width:100%">
        <tr>
            <th>tenure</th>
            <th>interest</th>
            <th>amount</th>
        </tr>
        <?php if ($block->getEmiCollection()) {
            foreach ($block->getEmiCollection() as $item) {
                if (($block->getGender() == '1') && ($item->getData('gender') == 'male')) {
                    ?>
                    <tr>
                        <td><?php echo $item->getData('month'); ?></td>
                        <td><?php echo $item->getData('interest'); ?></td>
                        <td><?php echo($block->getCurrentProduct() * $item->getData('interest') / 100 + $block->getCurrentProduct()); ?></td>
                    </tr>
                <?php } elseif (($block->getGender() == '2') && ($item->getData('gender') == 'female')) {
                    ?>
                    <tr>
                        <td><?php echo $item->getData('month'); ?></td>
                        <td><?php echo $item->getData('interest'); ?></td>
                        <td><?php echo($block->getCurrentProduct() * $item->getData('interest') / 100 + $block->getCurrentProduct()); ?></td>
                    </tr>
                <?php } elseif ((!$block->getCustomerId()) && ($item->getData('gender') == 'male')) {
                    ?>
                    <tr>
                        <td><?php echo $item->getData('month'); ?></td>
                        <td><?php echo $item->getData('interest'); ?></td>
                        <td><?php echo($block->getCurrentProduct() * $item->getData('interest') / 100 + $block->getCurrentProduct()); ?></td>
                    </tr>
                    <?php
                } elseif (($block->getGender() == '3') && ($item->getData('gender') == 'male')) {
                    ?>
                    <tr>
                        <td><?php echo $item->getData('month'); ?></td>
                        <td><?php echo $item->getData('interest'); ?></td>
                        <td><?php echo($block->getCurrentProduct() * $item->getData('interest') / 100 + $block->getCurrentProduct()); ?></td>
                    </tr>
                <?php } elseif (($block->getGender() == '0') && ($item->getData('gender') == 'male')) {
                    ?>
                    <tr>
                        <td><?php echo $item->getData('month'); ?></td>
                        <td><?php echo $item->getData('interest'); ?></td>
                        <td><?php echo($block->getCurrentProduct() * $item->getData('interest') / 100 + $block->getCurrentProduct()); ?></td>
                    </tr>
                <?php }
            }
        }

        ?>
    </table>
    </span>

</div>
<script>
    // When the user clicks on div, open the popup
    function myFunction() {
        var popup = document.getElementById("myPopup");
        popup.classList.toggle("show");
    }
</script>
<style>
    table, th, td {
        border: 1px solid black;
    }
</style>
<style>
    /* Popup container - can be anything you want */
    .popup {
        position: relative;
        display: inline-block;
        cursor: pointer;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    /* The actual popup */
    .popup .popuptext {
        visibility: hidden;
        width: 258px;
        background-color: #555;
        color: #fff;
        text-align: center;
        border-radius: 6px;
        padding: 8px 0;
        position: absolute;
        z-index: 1;
        bottom: 125%;
        left: 50%;
        margin-left: -80px;
    }

    /* Popup arrow */
    .popup .popuptext::after {
        content: "";
        position: absolute;
        top: 100%;
        left: 50%;
        margin-left: -5px;
        border-width: 5px;
        border-style: solid;
        border-color: #555 transparent transparent transparent;
    }

    /* Toggle this class - hide and show the popup */
    .popup .show {
        visibility: visible;
        -webkit-animation: fadeIn 1s;
        animation: fadeIn 1s;
    }

    /* Add animation (fade in the popup) */
    @-webkit-keyframes fadeIn {
        from {opacity: 0;}
        to {opacity: 1;}
    }

    @keyframes fadeIn {
        from {opacity: 0;}
        to {opacity:1 ;}
    }
</style>
